# Next.js Frontend Multi-stage Dockerfile
FROM node:20-alpine AS base

WORKDIR /app

COPY frontend/package.json ./
RUN npm install

COPY frontend ./

RUN npm run build

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "start"]
