"""Weather dataset converters: CSV data logger import and user-defined engineering weather generator."""

import csv
import io
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Any, List, Optional
import pandas as pd

from backend.weather.validator import WeatherValidator, WeatherClassification


def elevation_to_barometric_pressure_pa(elevation_m: float) -> float:
    """Calculate standard atmospheric barometric pressure in Pascals from elevation in meters."""
    elev = max(0.0, min(8848.0, elevation_m))
    # Standard barometric formula: P = 101325 * (1 - 2.25577e-5 * h)^5.25588
    pressure = 101325.0 * ((1.0 - 2.25577e-5 * elev) ** 5.25588)
    return max(30000.0, min(108000.0, round(pressure, 0)))


class CSVWeatherConverter:
    """Convert tabular CSV meteorological station logs into standard EnergyPlus EPW files."""

    REQUIRED_VARS = ["dry_bulb_temp_c"]

    @classmethod
    def convert_csv_to_epw(
        cls,
        csv_content: str,
        location_name: str,
        latitude: float,
        longitude: float,
        elevation_m: float,
        output_dir: Optional[Path] = None,
        time_zone: Optional[float] = None,
    ) -> Path:
        """Parse CSV content and write a valid EPW file."""
        df = pd.read_csv(io.StringIO(csv_content))
        df.columns = [c.strip().lower() for c in df.columns]

        # Check required columns
        temp_col = None
        for col in ["dry_bulb_temp_c", "temperature", "temp", "drybulb", "t2m", "air_temp"]:
            if col in df.columns:
                temp_col = col
                break
        if not temp_col:
            raise ValueError(f"CSV missing dry bulb temperature column. Found columns: {list(df.columns)}")

        rh_col = None
        for col in ["relative_humidity", "rh", "humidity", "rh2m", "rh_pct"]:
            if col in df.columns:
                rh_col = col
                break

        solar_col = None
        for col in ["solar_radiation_wm2", "ghi", "solar", "global_horizontal", "solar_wm2"]:
            if col in df.columns:
                solar_col = col
                break

        wind_col = None
        for col in ["wind_speed_ms", "wind_speed", "wind", "ws"]:
            if col in df.columns:
                wind_col = col
                break

        target_dir = output_dir or Path("storage/weather").resolve()
        target_dir.mkdir(parents=True, exist_ok=True)
        safe_loc = "".join(c if c.isalnum() else "_" for c in location_name).strip("_")
        epw_path = target_dir / f"CSV_IMPORT_{safe_loc}_{latitude:.2f}N_{longitude:.2f}E.epw"

        tz = time_zone if time_zone is not None else round(longitude / 15.0 * 2) / 2
        std_pressure = elevation_to_barometric_pressure_pa(elevation_m)

        lines = [
            f"LOCATION,{location_name},CSV-IMPORT,IND,Field Weather Station,999999,{latitude:.4f},{longitude:.4f},{tz:.1f},{elevation_m:.1f}",
            "DESIGN CONDITIONS,0",
            "TYPICAL/EXTREME PERIODS,0",
            "GROUND TEMPERATURES,0",
            "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
            "COMMENTS 1,CSV Station Log Imported Meteorological Data",
            "COMMENTS 2,Generated by SIH 2026 High Altitude Shelter Platform",
            f"DATA PERIODS,1,1,Data,Sunday,1,1,12,31",
        ]

        # Process rows
        for idx, row in df.iterrows():
            hour_val = int(row.get("hour", (idx % 24) + 1))
            if hour_val == 0:
                hour_val = 24
            month_val = int(row.get("month", 1))
            day_val = int(row.get("day", (idx // 24) + 1))
            year_val = int(row.get("year", 2023))

            dry_bulb = float(row[temp_col])
            rel_hum = float(row[rh_col]) if rh_col else 50.0
            rel_hum = max(1.0, min(100.0, rel_hum))
            wind_spd = float(row[wind_col]) if wind_col else 2.0
            ghi = float(row[solar_col]) if solar_col else 0.0
            dni = max(0.0, ghi * 1.1) if ghi > 0 else 0.0
            dhi = max(0.0, ghi * 0.4) if ghi > 0 else 0.0

            # Calculate dew point and infrared
            a, b = 17.27, 237.7
            alpha = ((a * dry_bulb) / (b + dry_bulb)) + math.log(rel_hum / 100.0)
            dew_point = (b * alpha) / (a - alpha)

            ir_sky = max(100.0, min(500.0, 5.67e-8 * ((dry_bulb + 273.15) ** 4) * 0.75))

            epw_row = [
                str(year_val), str(month_val), str(day_val), str(hour_val), "60",
                "?9?9?9?9E0?9?9?9?9?9?9?9?9",
                f"{dry_bulb:.2f}",
                f"{dew_point:.2f}",
                f"{rel_hum:.1f}",
                f"{std_pressure:.0f}",
                "1367", "1367",
                f"{ir_sky:.1f}",
                f"{ghi:.0f}",
                f"{dni:.0f}",
                f"{dhi:.0f}",
                "0", "0", "0", "0",
                "0", f"{wind_spd:.2f}",
                "5", "5",
                "9999", "99999",
                "0", "0", "0.0", "0.0", "0.0", "0", "0.2", "0.0", "0.0"
            ]
            lines.append(",".join(epw_row))

        with open(epw_path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines) + "\n")

        return epw_path


class ManualWeatherGenerator:
    """Generate engineering design days or stress test weather datasets from physical parameters."""

    @classmethod
    def generate_custom_weather(
        cls,
        location_name: str,
        latitude: float,
        longitude: float,
        elevation_m: float,
        design_winter_min_c: float,
        design_summer_max_c: float,
        diurnal_range_c: float = 14.0,
        peak_solar_dni_wm2: float = 850.0,
        wind_speed_ms: float = 3.5,
        num_days: int = 3,
        start_month: int = 1,
        start_day: int = 1,
        output_dir: Optional[Path] = None,
    ) -> Path:
        """Synthesize an authentic physics-consistent multi-day EPW file tagged as USER_DEFINED."""
        target_dir = output_dir or Path("storage/weather").resolve()
        target_dir.mkdir(parents=True, exist_ok=True)
        safe_loc = "".join(c if c.isalnum() else "_" for c in location_name).strip("_")
        epw_filename = f"USER_DEFINED_{safe_loc}_{latitude:.2f}N_{elevation_m:.0f}m.epw"
        epw_path = target_dir / epw_filename

        time_zone = round(longitude / 15.0 * 2) / 2
        baro_pa = elevation_to_barometric_pressure_pa(elevation_m)
        mean_t = design_winter_min_c + (diurnal_range_c / 2.0)

        lines = [
            f"LOCATION,{location_name},USER-DESIGN,IND,USER_DEFINED Parametric Design Day,999999,{latitude:.4f},{longitude:.4f},{time_zone:.1f},{elevation_m:.1f}",
            "DESIGN CONDITIONS,0",
            "TYPICAL/EXTREME PERIODS,0",
            "GROUND TEMPERATURES,0",
            "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0",
            "COMMENTS 1,Custom User-Defined High Altitude Extreme Engineering Design Day",
            "COMMENTS 2,Classified as USER_DEFINED under Weather Data Policy",
            f"DATA PERIODS,1,1,Data,Sunday,{start_month},{start_day},{start_month},{start_day + num_days - 1}",
        ]

        year = 2024
        for d in range(num_days):
            cur_day = start_day + d
            for h in range(1, 25):
                # Diurnal temperature cycle: lowest at 05:00, highest at 14:00
                temp_c = mean_t + (diurnal_range_c / 2.0) * math.sin(((h - 9.0) / 24.0) * 2.0 * math.pi)

                # Solar bell curve between 07:00 and 17:00
                if 7 <= h <= 17:
                    solar_factor = math.sin(((h - 7.0) / 10.0) * math.pi)
                    dni = peak_solar_dni_wm2 * solar_factor
                    ghi = dni * math.sin(((h - 7.0) / 10.0) * math.pi) * 0.85
                    dhi = ghi * 0.25
                else:
                    dni = 0.0
                    ghi = 0.0
                    dhi = 0.0

                rel_hum = max(10.0, min(95.0, 50.0 - 15.0 * math.sin(((h - 9.0) / 24.0) * 2.0 * math.pi)))
                dew_point = temp_c - ((100.0 - rel_hum) / 5.0)

                # Sky infrared
                temp_k = temp_c + 273.15
                ir_sky = max(60.0, min(500.0, 0.72 * 5.67e-8 * (temp_k ** 4)))

                row = [
                    str(year), str(start_month), str(cur_day), str(h), "60",
                    "?9?9?9?9E0?9?9?9?9?9?9?9?9",
                    f"{temp_c:.2f}",
                    f"{dew_point:.2f}",
                    f"{rel_hum:.1f}",
                    f"{baro_pa:.0f}",
                    "1367", "1367",
                    f"{ir_sky:.1f}",
                    f"{ghi:.0f}",
                    f"{dni:.0f}",
                    f"{dhi:.0f}",
                    "0", "0", "0", "0",
                    "270", f"{wind_speed_ms:.2f}",
                    "3", "3",
                    "9999", "99999",
                    "0", "0", "0.0", "0.0", "0.0", "0", "0.2", "0.0", "0.0"
                ]
                lines.append(",".join(row))

        with open(epw_path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines) + "\n")

        return epw_path
